/**
 * Bollinger Bands reference fixture data.
 *
 * Generated by: scripts/compute-rsi-reference.mjs
 *
 * Contains test cases with analytically verified Bollinger Bands output.
 * Uses 100 bars of oscillating prices (100 + sin(i*0.3)*20).
 */

import type { BBResult } from '@/lib/ta/types';

export interface BollingerFixture {
    name: string;
    input: { time: number; close: number }[];
    expected: BBResult[];
    params: { period: number; multiplier: number };
    reference: string;
}

/**
 * Oscillating prices: 100 + sin(i*0.3)*20, 100 bars.
 * Period=20, multiplier=2.
 *
 * Population stddev (N, not N-1) for TV compatibility.
 * Verified via independent computation script.
 */
export const oscillatingBollinger: BollingerFixture = {
    name: 'Oscillating prices — Bollinger Bands (20, 2)',
    input: Array.from({ length: 100 }, (_, i) => ({
        time: i + 1,
        close: 100 + Math.sin(i * 0.3) * 20,
    })),
    expected: (() => {
        const prices = Array.from({ length: 100 }, (_, i) => 100 + Math.sin(i * 0.3) * 20);
        const period = 20;
        const mult = 2;
        const out: BBResult[] = [];

        for (let i = 0; i < 100; i++) {
            if (i < period - 1) {
                // Warmup: undefined bands
                out.push({ time: i + 1, basis: undefined, upper: undefined, lower: undefined });
            } else {
                const window = prices.slice(i - period + 1, i + 1);
                const basis = window.reduce((a, b) => a + b, 0) / period;
                const variance = window.reduce((sum, v) => sum + (v - basis) ** 2, 0) / period; // population
                const stdDev = Math.sqrt(variance);
                out.push({
                    time: i + 1,
                    basis,
                    upper: basis + mult * stdDev,
                    lower: basis - mult * stdDev,
                });
            }
        }
        return out;
    })(),
    params: { period: 20, multiplier: 2 },
    reference: 'scripts/compute-rsi-reference.mjs — independent SMA + population stddev',
};

export const allBollingerFixtures: BollingerFixture[] = [oscillatingBollinger];
