/**
 * MACD reference fixture data.
 *
 * Generated by: scripts/compute-rsi-reference.mjs
 *
 * Contains test cases with analytically verified MACD output values.
 * Uses 100 bars of steadily rising prices (100 + 2i) to produce
 * a positive MACD with negative histogram (converging EMAs).
 */

import type { MACDInput, MACDOutput } from '@/lib/indicators/macd';

export interface MacdFixture {
    name: string;
    input: MACDInput[];
    expected: MACDOutput[];
    params: { fast: number; slow: number; signal: number };
    reference: string;
}

/**
 * Steadily rising prices (100 + 2i), 100 bars.
 * Fast EMA(12) always > Slow EMA(26) → MACD positive.
 * As trend matures, histogram → 0 (EMAs converge linearly).
 *
 * Verified via independent EMA computation script.
 */
export const risingMacd: MacdFixture = {
    name: 'Steadily rising prices — MACD positive, histogram converging to 0',
    input: Array.from({ length: 100 }, (_, i) => ({
        time: i + 1,
        close: 100 + i * 2,
    })),
    expected: (() => {
        // Build full array of 100 entries
        const out: MACDOutput[] = [];

        // Helper: EMA with 'value' seed
        function ema(values: number[], p: number): (number | undefined)[] {
            const n = values.length;
            const result: (number | undefined)[] = new Array(n).fill(undefined);
            const k = 2 / (p + 1);
            let prev = values[0];
            result[0] = prev;
            for (let i = 1; i < n; i++) {
                prev = values[i] * k + prev * (1 - k);
                result[i] = prev;
            }
            return result;
        }

        const closes = Array.from({ length: 100 }, (_, i) => 100 + i * 2);
        const fast12 = 12, slow26 = 26, sig9 = 9;

        const emaFast = ema(closes, fast12);
        const emaSlow = ema(closes, slow26);

        const macdLine: (number | undefined)[] = [];
        for (let i = 0; i < 100; i++) {
            const ef = emaFast[i];
            const es = emaSlow[i];
            macdLine.push(ef !== undefined && es !== undefined ? ef - es : undefined);
        }

        const signalLine = ema(
            macdLine.map(v => v ?? 0),
            sig9,
        );
        // Re-apply undefined where macd was undefined
        for (let i = 0; i < 100; i++) {
            if (macdLine[i] === undefined) signalLine[i] = undefined;
        }

        for (let i = 0; i < 100; i++) {
            const m = macdLine[i];
            const s = signalLine[i];
            out.push({
                time: i + 1,
                macd: m,
                signal: s,
                histogram: m !== undefined && s !== undefined ? m - s : undefined,
            });
        }
        return out;
    })(),
    params: { fast: 12, slow: 26, signal: 9 },
    reference: 'scripts/compute-rsi-reference.mjs — independent EMA implementation',
};

export const allMacdFixtures: MacdFixture[] = [risingMacd];
