/**
 * RSI reference fixture data.
 *
 * Generated by: scripts/compute-rsi-reference.mjs
 *
 * Contains test cases with analytically verified RSI output values.
 * These serve as "reference values" — when actual TradingView Pine Script
 * exports are available, replace the last value in expected array with
 * the TV value and adjust tolerance to 1e-4.
 */

import type { RSIInput, RSIOutput } from '@/lib/indicators/rsi';

export interface RsiFixture {
    name: string;
    input: RSIInput[];
    expected: RSIOutput[];
    params: { length: number; maLength: number };
    reference: string;
}

/**
 * Case 1: Flat prices (all 100).
 * - All gains = 0, all losses = 0
 * - SMMA(zeros, 14) → 0 everywhere
 * - loss === 0 → RSI = 100
 * - SMA(100s, 14) → 100 everywhere
 */
export const flatPricesRsi: RsiFixture = {
    name: 'Flat prices → RSI = 100 everywhere after warmup',
    input: Array.from({ length: 30 }, (_, i) => ({
        time: i + 1,
        close: 100,
    })),
    expected: (() => {
        const out: RSIOutput[] = [];
        for (let i = 0; i < 30; i++) {
            out.push({
                time: i + 1,
                rsi: i >= 13 ? 100 : undefined,
                // BUGFIX: SMA now divides by definedCount (not period), so MA = 100
                // as soon as the first RSI value (100) enters the window.
                ma: i >= 13 ? 100 : undefined,
                confidence: 0,
            });
        }
        return out;
    })(),
    params: { length: 14, maLength: 14 },
    reference: 'Mathematical: SMMA(0)/SMMA(0), loss=0 → RSI=100',
};

/**
 * Case 2: Steadily rising prices (100 + i).
 * - All gains = 1, all losses = 0
 * - SMMA(1s, 14) → 1, SMMA(0s, 14) → 0
 * - loss === 0 → RSI = 100
 */
export const risingPricesRsi: RsiFixture = {
    name: 'Steadily rising → RSI = 100 everywhere after warmup',
    input: Array.from({ length: 30 }, (_, i) => ({
        time: i + 1,
        close: 100 + i,
    })),
    expected: (() => {
        const out: RSIOutput[] = [];
        for (let i = 0; i < 30; i++) {
            out.push({
                time: i + 1,
                rsi: i >= 13 ? 100 : undefined,
                // BUGFIX: SMA now divides by definedCount, so MA = 100 from bar 13
                ma: i >= 13 ? 100 : undefined,
                confidence: i >= 14 ? 1 : 0,
            });
        }
        return out;
    })(),
    params: { length: 14, maLength: 14 },
    reference: 'Mathematical: gain=1, loss=0 → RSI=100',
};

/**
 * Case 3: Steadily falling prices (200 - i).
 * - All gains = 0, all losses = 1
 * - rs = 0/1 = 0 → RSI = 100 - 100/(1+0) = 0
 */
export const fallingPricesRsi: RsiFixture = {
    name: 'Steadily falling → RSI = 0 everywhere after warmup',
    input: Array.from({ length: 30 }, (_, i) => ({
        time: i + 1,
        close: 200 - i,
    })),
    expected: (() => {
        const out: RSIOutput[] = [];
        for (let i = 0; i < 30; i++) {
            out.push({
                time: i + 1,
                rsi: i >= 13 ? 0 : undefined,
                ma: i >= 13 ? 0 : undefined,
                confidence: i >= 14 ? 1 : 0,
            });
        }
        return out;
    })(),
    params: { length: 14, maLength: 14 },
    reference: 'Mathematical: gain=0, loss=1, rs=0 → RSI=0',
};

/**
 * Case 4: Oscillating prices (wide swings, period=5).
 * Pre-computed via scripts/compute-rsi-reference.mjs
 *
 * Prices: [100, 102, 98, 104, 96, 106, 94, 108, 92, 110,
 *           90, 112, 88, 114, 86, 116, 84, 118, 82, 120]
 * RSI(5) with MA(3) — provides non-trivial reference values.
 *
 * SPRINT 5: SMMA tohumu (i=length-1=4, time=5) confidence=0.
 * Warmup döneminin son barı (SMA seed) güven=0 olarak işaretlenir;
 * i>=length barları (time>=6) tam ısınma ile confidence=1 alır.
 * Bu tutarlılık rising/falling fixture'larıyla hizalanmıştır.
 */
export const oscillatingRsi: RsiFixture = {
    name: 'Oscillating prices — verified via independent SMMA computation',
    input: [
        { time: 1, close: 100 }, { time: 2, close: 102 },
        { time: 3, close: 98 }, { time: 4, close: 104 },
        { time: 5, close: 96 }, { time: 6, close: 106 },
        { time: 7, close: 94 }, { time: 8, close: 108 },
        { time: 9, close: 92 }, { time: 10, close: 110 },
        { time: 11, close: 90 }, { time: 12, close: 112 },
        { time: 13, close: 88 }, { time: 14, close: 114 },
        { time: 15, close: 86 }, { time: 16, close: 116 },
        { time: 17, close: 84 }, { time: 18, close: 118 },
        { time: 19, close: 82 }, { time: 20, close: 120 },
    ],
    expected: [
        { time: 1, rsi: undefined, ma: undefined, confidence: 0 },
        { time: 2, rsi: undefined, ma: undefined, confidence: 0 },
        { time: 3, rsi: undefined, ma: undefined, confidence: 0 },
        { time: 4, rsi: undefined, ma: undefined, confidence: 0 },
        // BUGFIX: SMA now divides by definedCount — first bar with 1 defined value → 40/1=40
        { time: 5, rsi: 40, ma: 40, confidence: 0 },
        // BUGFIX: second bar with 2 defined values → (40+63.0769)/2=51.5385
        { time: 6, rsi: 63.07692307692307, ma: 51.53846153846154, confidence: 1 },
        { time: 7, rsi: 39.99999999999999, ma: 47.692307692307686, confidence: 1 },
        { time: 8, rsi: 60.87475149105367, ma: 54.65055818932558, confidence: 1 },
        { time: 9, rsi: 40.66401062416998, ma: 47.17958737174121, confidence: 1 },
        { time: 10, rsi: 59.5495954280541, ma: 53.69611918109258, confidence: 1 },
        { time: 11, rsi: 41.29485393655216, ma: 47.16948666292541, confidence: 1 },
        { time: 12, rsi: 58.70202866246983, ma: 53.182159342358695, confidence: 1 },
        { time: 13, rsi: 41.800328739659314, ma: 47.26573711289377, confidence: 1 },
        { time: 14, rsi: 58.12661660078135, ma: 52.87632466763683, confidence: 1 },
        { time: 15, rsi: 42.193328704719264, ma: 47.373424681719975, confidence: 1 },
        { time: 16, rsi: 57.71634506666911, ma: 52.67876345738991, confidence: 1 },
        { time: 17, rsi: 42.49960083245744, ma: 47.46975820128194, confidence: 1 },
        { time: 18, rsi: 57.41204060757434, ma: 52.5426621689003, confidence: 1 },
        { time: 19, rsi: 42.74112071995015, ma: 47.550920719993975, confidence: 1 },
        { time: 20, rsi: 57.17897190711845, ma: 52.44404441154765, confidence: 1 },
    ],
    params: { length: 5, maLength: 3 },
    reference: 'scripts/compute-rsi-reference.mjs — independent SMMA implementation',
};

/**
 * All RSI fixtures for batch testing.
 */
export const allRsiFixtures: RsiFixture[] = [
    flatPricesRsi,
    risingPricesRsi,
    fallingPricesRsi,
    oscillatingRsi,
];
